'use client';
import './globals.css';
import { Inter } from 'next/font/google';
import { ApolloProvider } from '@apollo/client';
import { ApolloService } from '@/services/apollo-service';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <ApolloProvider client={ApolloService}>
                <body className={inter.className}>{children}</body>
            </ApolloProvider>
        </html>
    )
}


